Biographic page set up
eroiyo/Review-Practice pull request #1
Opened 2021-06-02 09:43 UTC by eroiyo

First Release

2021-06-02 10:52 UTC, eroiyo commented
Hi @eroiyo, 

Good job so far! 🔥🔥 You have done a lot of effort in this project, and we can see part of your HTML and CSS knowledge there looks like you very near to be a Micronaut!

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

![image](https://user-images.githubusercontent.com/59938389/120467264-fee1e200-c36d-11eb-8ba2-dd98bea7ed37.png)

- [ ] There are no equal spaces between elements, that is needed in order to your code be more readable and easy to understand for your partners

![image](https://user-images.githubusercontent.com/59938389/120467547-48cac800-c36e-11eb-88d2-e8236e2283a0.png)

- [ ] There it's an unused element, that can be very confusing if someone it's reading the code for the first time

![image](https://user-images.githubusercontent.com/59938389/120467944-abbc5f00-c36e-11eb-9eb4-4c5b03aeb396.png)

- [ ] that h2 dont have a close tag, they are important, if you dont put close tags, the page will be penalized for internet searchers like google

for more information about HTML practices click on [this link]https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-06-02 22:52 UTC, Spayco requested changes
Hi @eroiyo, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] it's best to utilize the "Review changes" feature from GitHub
- [ ] please include those changes using [inline comments](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request) (that way you won't have to screenshot pieces of code)
- [ ]  kindly phrase the comments politely, as suggestions instead of orders. For example:

  * This is a polite suggestion: *"I think it would be better to use semantic tags"*
  * This reads as an order: *"Use semantic tags"*
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 09:33 UTC, eroiyo commented
Hi @eroiyo, 

Good job so far! 🔥🔥 You have done a lot of effort in this project, and we can see part of your HTML and CSS knowledge there looks like you very near to be a Micronaut!

There are some issues that you still need to work on to go to the next project but you are almost there!

2021-06-03 09:54 UTC, eroiyo reviewed
.

2021-06-03 09:54 UTC, eroiyo commented on style.css
> +}
- [ ] You should try to use equal spaces between elements, that will make your code more readable, so your future coworkers would understand your code more easily 👨‍💻

2021-06-03 09:54 UTC, eroiyo commented on style.css
> +}
- [ ] I suggest to you to deleted unused piece of code, that will make it more accessible and light 🕊️

2021-06-03 09:54 UTC, eroiyo commented on style.css
> +}
- [ ] I recommend to you to use 2 space indentation, it's very important to follow the code standard 📘

2021-06-03 09:54 UTC, eroiyo commented on index.html
> +</html>
- [ ] I see that h2 dont have a close tag, I recommend you to close it, they are important, if you dont put close tags, the page will be penalized for internet searchers like google.

For more information about HTML practices, click on [this link](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-06-03 10:01 UTC, eroiyo reviewed
For more information about HTML practices, click on [this link](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-06-03 12:02 UTC, nidalaa commented on style.css
> +}
Great comment - polite, clear, and explaining why the change is expected. And you also used an emoji! 😍

2021-06-03 12:02 UTC, nidalaa commented on style.css
> +}
Great comment - polite, clear, and explaining why the change is expected. And you also used an emoji! 😍

2021-06-03 12:02 UTC, nidalaa commented on style.css
> +}
Great comment - polite, clear, and explaining why the change is expected. And you also used an emoji! 😍

2021-06-03 12:02 UTC, nidalaa commented on index.html
> +</html>
Great comment - polite, clear, and explaining why the change is expected.

2021-06-03 12:05 UTC, nidalaa approved these changes
Hi @eroiyo , 

Your project is complete!  This review looks way better with inline comments instead of screenshots, isn't it? I can see that you tried to use the "Review changes" feature after you added inline comments, that's why you have 2 summary comments. It is not bad "per se" - in the end, you managed to communicate what was there to communicate, so great job. But you can revisit [this part of the lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-use-github-features) to make sure that you use GH review features in the most efficient way :)

 There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Students Handbook](https://www.notion.so/microverse/Project-reviews-022203ea6dd944b296b005533a19dcbe#cb67391d09f54bd98d6fed6ba24a4074) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-07 15:37 UTC, closed without merging